# NumPy — Numerical Python

NumPy is the standard library for working with numerical data in Python.

You use it when you need to:
- store many numbers efficiently
- work with vectors, matrices, and multidimensional grids
- run fast math operations on entire datasets

A key idea: **NumPy arrays are designed for numeric computation**. They are usually faster and more convenient than plain Python lists for large numerical workloads.

## How to use this notebook

- Run each code cell with `Shift + Enter`.
- After running a cell, change values and rerun.
- Focus on understanding shapes and indexing: most bugs in NumPy come from shape mistakes.

## 0. Install and import

If you are running this locally and NumPy is missing, install it with:

```bash
pip install numpy
```

Now import it:

In [12]:
import numpy as np

# 1. Why NumPy arrays?

Python lists are flexible: they can contain mixed types.

That flexibility is useful, but it also means:
- extra memory overhead
- slower numerical operations

NumPy arrays are different:
- a single numeric type (for example all `float64`)
- stored in contiguous memory (good for fast access)
- operations are vectorized (apply to many elements at once)

The result: code that is often shorter and faster for numerical tasks.

### Quick comparison: list vs array

The goal is not to benchmark here, but to notice the different *style of computation*.

In [14]:
py_list = [10.0, 12.0, 11.5, 13.2]
np_arr = np.array(py_list)

print("Python list:", py_list)
print("NumPy array:", np_arr)
print("Type of list:", type(py_list))
print("Type of array:", type(np_arr))

Python list: [10.0, 12.0, 11.5, 13.2]
NumPy array: [10.  12.  11.5 13.2]
Type of list: <class 'list'>
Type of array: <class 'numpy.ndarray'>


# 2. NumPy data types (dtypes)

NumPy defines its own numeric data types (called **dtypes**), such as:
- integers: `int8`, `int16`, `int32`, `int64`
- unsigned integers: `uint8`, ..., `uint64`
- floats: `float16`, `float32`, `float64`
- boolean: `bool`

Most of the time you do not need to choose a dtype manually.
But it is useful to know it exists (especially for memory and precision control).

In [15]:
a = np.array([1, 2, 3])
b = np.array([1.0, 2.0, 3.0])

print(a, a.dtype)
print(b, b.dtype)

[1 2 3] int64
[1. 2. 3.] float64


### Forcing a dtype

Sometimes you want to force a specific dtype.

In [16]:
c = np.array([1, 2, 3], dtype=np.float32)
print(c, c.dtype)

[1. 2. 3.] float32


# 3. Multidimensional arrays

A multidimensional array is a collection of elements arranged along one or more **axes**.

Common cases:
- 1D array: a vector
- 2D array: a matrix (rows and columns)
- 3D array: a stack of matrices (for example, a time sequence of 2D grids)

You can build NumPy arrays directly from nested Python lists.

In [17]:
v = np.array([1, 2, 3])
m = np.array([[1, 2, 3],
              [4, 5, 6]])
cube = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

print("Vector (1D):\n", v)
print("\nMatrix (2D):\n", m)
print("\n3D array shape:", cube.shape)

Vector (1D):
 [1 2 3]

Matrix (2D):
 [[1 2 3]
 [4 5 6]]

3D array shape: (3, 2, 3)


## Axes and shape

Every NumPy array has:
- `ndim`: number of dimensions
- `shape`: how many elements along each axis
- `size`: total number of elements

Example: shape `(2, 3)` means 2 rows and 3 columns.

In [18]:
x = np.array([[2, 3, 4],
              [5, 6, 7]])

print(x)
print("ndim:", x.ndim)
print("shape:", x.shape)
print("size:", x.size)

[[2 3 4]
 [5 6 7]]
ndim: 2
shape: (2, 3)
size: 6


## Row vector vs column vector

A frequent source of confusion is that:
- a 1D array with shape `(3,)` is a *vector*
- a column vector is usually represented as a 2D array with shape `(3, 1)`

Both can store three numbers, but shapes affect matrix operations and broadcasting.

In [19]:
row_like = np.array([0.1, 0.2, 0.3])
col = np.array([[0.1], [0.2], [0.3]])

print("row_like shape:", row_like.shape)
print("col shape:", col.shape)
print("\nrow_like:\n", row_like)
print("\ncol:\n", col)

row_like shape: (3,)
col shape: (3, 1)

row_like:
 [0.1 0.2 0.3]

col:
 [[0.1]
 [0.2]
 [0.3]]


# 4. Creating arrays (practical patterns)

You can create arrays:
- from Python lists
- from scratch with zeros/ones/constant values
- as sequences with `linspace`, `arange` and `logspace`
- as random data (useful for simulation and testing)

## 4.1 From scratch: zeros, ones, full

In [21]:
a0 = np.zeros((2, 3)) # an array of all zeros with 2 rows and 3 columns
a1 = np.ones((2, 3))# an array of all ones with 2 rows and 3 columns
a2 = np.full((2, 3), 1.1)  # an array filled with the value you want (1.1 this time) with 2 rows and 3 columns

print("zeros:\n", a0)
print("\nones:\n", a1)
print("\nfull (1.1):\n", a2)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

full (1.1):
 [[1.1 1.1 1.1]
 [1.1 1.1 1.1]]


## 4.2 Sequences: linspace and arange

- `linspace(start, stop, num)` includes both ends and creates `num` points.
- `logspace(start, stop, step)` includes both endpoints and returns `num` points spaced evenly on a logarithmic scale (i.e., base\*\*start to base\*\*stop, with base=10 by default)

- `arange(start, stop, step)` excludes `stop` and uses a step.

In [ ]:
time = np.linspace(0, 1, 11)    
logs = np.logspace(-1, 1, 10)  

levels = np.arange(0, 10, 2)   

print("time:", time)
print("logs:", logs)

print("levels:", levels)

time: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
logs: [ 0.1         0.16681005  0.27825594  0.46415888  0.77426368  1.29154967
  2.15443469  3.59381366  5.9948425  10.        ]
levels: [0 2 4 6 8]


## 4.3 Random arrays

Random arrays are useful for:
- quick simulations
- testing code without needing a dataset

Two common generators:
- `np.random.random(shape)` uniform in [0, 1)
- `np.random.normal(mean, std, shape)` Gaussian distribution

In [29]:
u = np.random.random((2, 3))
g = np.random.normal(0.0, 1.0, (2, 3))

print("uniform:\n", u)
print("\nnormal:\n", g)

uniform:
 [[0.89800654 0.86936657 0.45035045]
 [0.34713924 0.42855221 0.01423801]]

normal:
 [[-0.24161549 -0.39878053  0.11788549]
 [ 0.98092807  0.48217108  0.30329374]]


# 5. Computation with arrays (vectorized operations)

NumPy supports **element-wise operations**, meaning the operation is applied to each element.

This includes:
- binary operations: `+`, `-`, `*`, `/`, `**`, `//`, `%`
- unary functions: `abs`, `exp`, `log`, `sin`, ...

A key benefit: you write compact code without explicit loops for many tasks.

**QUIZ: Do you remember what happens if you use the binary operator `+` on two lists?** 

## 5.1 Binary operations (same shape)

In [30]:
x = np.array([[1, 1],
              [2, 2]])
y = np.array([[3, 4],
              [6, 5]])

print("x:\n", x)
print("\ny:\n", y)
print("\nx * y (element-wise):\n", x * y)
print("\nx + y:\n", x + y)

x:
 [[1 1]
 [2 2]]

y:
 [[3 4]
 [6 5]]

x * y (element-wise):
 [[ 3  4]
 [12 10]]

x + y:
 [[4 5]
 [8 7]]


## 5.2 Unary operations (apply to each element)

These functions return a new array (the original array is not modified).

In [31]:
x = np.array([[1, 1],
              [2, 2]])

print("exp(x):\n", np.exp(x))
print("abs([-1, 2, -3]):", np.abs(np.array([-1, 2, -3])))

exp(x):
 [[2.71828183 2.71828183]
 [7.3890561  7.3890561 ]]
abs([-1, 2, -3]): [1 2 3]


# 6. Aggregate functions

Aggregate functions summarize an array into fewer values.

Common ones:
- `min`, `max`, `mean`, `std`, `sum`
- `argmin`, `argmax` (where the min/max occurs)

You can apply them:
- to the whole array
- along a specific axis (for example, per row or per column)

In [40]:
data = np.array([[10, 12, 14],
                 [9, 11, 13]])

print(data)
print("sum:", data.sum())


print()
print("mean:", data.mean())
print("min:", data.min())
print("argmax (flattened index):", data.argmax())

[[10 12 14]
 [ 9 11 13]]
sum: 69

mean: 11.5
min: 9
argmax (flattened index): 2


## Aggregate along an axis

For a 2D array:
- `axis=0` aggregates down the rows (result: one value per column)
- `axis=1` aggregates across the columns (result: one value per row)

Tip: read `axis=0` as "move along rows" and `axis=1` as "move along columns".

The output is often a 1D array (a vector).

In [41]:
x = np.array([[1, 7],
              [2, 4]])

print(x)
print("sum(axis=0) (per column):", x.sum(axis=0))
print("sum(axis=1) (per row):", x.sum(axis=1))

[[1 7]
 [2 4]]
sum(axis=0) (per column): [ 3 11]
sum(axis=1) (per row): [8 6]


# 7. Sorting

Sorting is a common operation when you need ordered values or want to rank measurements.

- `np.sort(x)` returns a sorted copy (does not modify `x`)
- `x.sort()` sorts in-place (modifies `x`)

By default, sorting happens along the last axis (`axis=-1`).

In [43]:
x = np.array([[2, 1, 3],
              [7, 9, 8]])
# axis=-1 -> we order the columns -> every row is sorted separately
print("original:\n", x)
print("sorted copy (rows):\n", np.sort(x))
print("original after np.sort (unchanged):\n", x)

original:
 [[2 1 3]
 [7 9 8]]
sorted copy (rows):
 [[1 2 3]
 [7 8 9]]
original after np.sort (unchanged):
 [[2 1 3]
 [7 9 8]]


## Sorting along a specific axis

- `axis=0` sorts each column
- `axis=1` sorts each row

Choose the axis based on what "direction" you want to sort.

In [ ]:
x = np.array([[2, 7, 3],
              [7, 2, 1]])

print("original:\n", x)
print("sorted by column (axis=0):\n", np.sort(x, axis=0))
print("sorted by row (axis=1):\n", np.sort(x, axis=1))

## argsort: sorting indices

`np.argsort(x)` returns the indices that would sort the array.

This is useful when:
- you want to reorder another array in the same way
- you want the ranking positions, not only the sorted values

In [46]:
x = np.array([2, 1, 3])
y= np.array([10,20, 30])
idx = np.argsort(x)

print("x:", x)
print("argsort indices:", idx)
print("x sorted using indices:", x[idx])
print("y sorted using indices of x:", y[idx])


x: [2 1 3]
argsort indices: [1 0 2]
x sorted using indices: [1 2 3]
y sorted using indices of x: [20 10 30]


## 8.1 1D dot 1D (inner product)

In [ ]:
x = np.array([1, 2, 3])
y = np.array([0, 2, 1])

print("dot:", np.dot(x, y)) #1*0 + 2*2 + 3*1

dot: 7


## 8.2 Matrix dot vector

In [51]:
A = np.array([[1, 1],
              [2, 2]])
v = np.array([2, 3])

print("A:\n", A)
print("v:", v)
print("A dot v:", np.dot(A, v)) #[1*2 + 1*3],
                                #[2*2 + 2*3]

A:
 [[1 1]
 [2 2]]
v: [2 3]
A dot v: [ 5 10]


In [53]:
# Order matters!
print("A dot v:", np.dot(v, A)) #[2*1 + 3*2],
                                #[2*1 + 3*2]

A dot v: [8 8]


## 8.3 Matrix dot matrix

In [54]:
A = np.array([[1, 1],
              [2, 2]])
B = np.array([[2, 2],
              [1, 1]])

print("A dot B:\n", np.dot(A, B))

A dot B:
 [[3 3]
 [6 6]]


# 9. Broadcasting

Broadcasting is a rule that allows operations between arrays of different shapes.

A typical use case:
- adding an offset vector to every row of a matrix
- scaling each column by a vector of factors

Broadcasting often removes the need for manual loops.

A simple mental model:
- if an array has shape 1 along a dimension, it can be "stretched" to match the other array
- if the shapes are incompatible, NumPy raises an error

## 9.1 Broadcasting example (common pattern)

Add a 1D vector to each row of a 2D matrix.

In [55]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
offset = np.array([10, 20, 30])

print("matrix:\n", matrix)
print("offset:", offset)
print("matrix + offset:\n", matrix + offset)

matrix:
 [[1 2 3]
 [4 5 6]]
offset: [10 20 30]
matrix + offset:
 [[11 22 33]
 [14 25 36]]


## 9.2 Broadcasting example with column vector

Here a column vector is added to each column (via broadcasting).

In [ ]:
x = np.array([1, 2, 3])
y = np.array([[11], [12], [13]])

print("x shape:", x.shape)
print("y shape:", y.shape)
print("x + y:\n", x + y)

## 9.3 A case that does NOT broadcast

If shapes are incompatible, NumPy raises an exception.

Try running this cell to see the error, then fix the shapes.

In [56]:
x = np.array([[1, 2],
              [3, 4],
              [5, 6]])
y = np.array([11, 12, 13])

# This will fail because shapes (3,2) and (3,) are incompatible for addition
# Uncomment to test
# z = x + y
# print(z)

print("x shape:", x.shape)
print("y shape:", y.shape)
print("Uncomment the lines above to see the broadcasting error.")

x shape: (3, 2)
y shape: (3,)
Uncomment the lines above to see the broadcasting error.


# 10. Accessing NumPy arrays

NumPy provides multiple ways to access data:
- simple indexing
- slicing
- masking (boolean selection)
- fancy indexing (select by index lists)
- combining methods

A very important idea:
- **slicing often creates a view** (changes can affect the original)
- masking and fancy indexing usually create **copies**

## 10.1 Simple indexing

Use `x[i, j]` to read or write a single element.

In [58]:
x = np.array([[2, 3, 4],
              [5, 6, 7]])

el = x[1, 2]
print("el =", el)

x[1, 2] = 1
print("updated x:\n", x)

el = 7
updated x:
 [[2 3 4]
 [5 6 1]]


### Negative indices

Negative indices count from the end.
- `-1` is the last element
- `-2` is the second-to-last element

In [59]:
x = np.array([[2, 3, 4],
              [5, 6, 7]])

print("x[0, -1] (last element of first row):", x[0, -1])
print("x[0, -2] (second from end):", x[0, -2])

x[0, -1] (last element of first row): 4
x[0, -2] (second from end): 3


## 10.2 Slicing

Slicing selects contiguous blocks:

```python
x[start:stop:step, ...]
```

Notes:
- `start` is included
- `stop` is excluded
- omit `start` to begin from the start
- omit `stop` to go until the end
- omit `step` for step = 1

In [60]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("x:\n", x)
print("\nAll rows, last two columns:\n", x[:, 1:])
print("\nFirst two rows, columns 0 and 2:\n", x[:2, ::2])

x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

All rows, last two columns:
 [[2 3]
 [5 6]
 [8 9]]

First two rows, columns 0 and 2:
 [[1 3]
 [4 6]]


## 10.3 Slicing creates views

A slice is often a **view** on the original array.

That means:
- if you modify the slice, you may modify the original array

This can be useful (fast, no extra memory), but it can also create unexpected changes.

Try the following cell and observe how `x` changes.

In [61]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

view = x[:, 1:]   # a view
view[:, :] = 0

print("view:\n", view)
print("\noriginal x (also changed):\n", x)

view:
 [[0 0]
 [0 0]
 [0 0]]

original x (also changed):
 [[1 0 0]
 [4 0 0]
 [7 0 0]]


### Avoid changing the original: use copy()

If you want an independent array, use `.copy()`.

In [62]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

sub = x[:, 1:].copy()  # independent copy
sub[:, :] = 0

print("sub:\n", sub)
print("\noriginal x (unchanged):\n", x)

sub:
 [[0 0]
 [0 0]
 [0 0]]

original x (unchanged):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 10.4 Masking (boolean selection)

Masking uses a boolean array to select values.

Steps:
1. build a mask with comparisons (`>`, `>=`, `<`, `==`, ...)
2. use `x[mask]` to select values

Important:
- the result is typically a 1D array of selected elements
- masking returns a **copy**, not a view

### Create masks

In [63]:
x = np.array([1.2, 4.1, 1.5, 4.5])
print("x:", x)
print("x > 4:", x > 4)

x2 = np.array([[1.2, 4.1],
               [1.5, 4.5]])
print("\nx2:\n", x2)
print("x2 >= 4:\n", x2 >= 4)

x: [1.2 4.1 1.5 4.5]
x > 4: [False  True False  True]

x2:
 [[1.2 4.1]
 [1.5 4.5]]
x2 >= 4:
 [[False  True]
 [False  True]]


### Select with a mask

In [64]:
x = np.array([1.2, 4.1, 1.5, 4.5])
print("selected:", x[x > 4])

x2 = np.array([[1.2, 4.1],
               [1.5, 4.5]])
print("selected from 2D:", x2[x2 >= 4])

selected: [4.1 4.5]
selected from 2D: [4.1 4.5]


### Update values using a mask

You can assign to selected elements directly.

In [65]:
x = np.array([1.2, 4.1, 1.5, 4.5])
x[x > 4] = 0
print(x)

[1.2 0.  1.5 0. ]


### Boolean operations on masks

You can combine masks with:
- `&` (and)
- `|` (or)
- `~` (not)

Example: select values between 1 and 5 (inclusive).

In [66]:
x = np.array([0.2, 1.2, 4.1, 5.8, 3.0])
mask = (x >= 1) & (x <= 5)
print("mask:", mask)
print("selected:", x[mask])

mask: [False  True  True False  True]
selected: [1.2 4.1 3. ]


## 10.5 Masking returns copies (not views)

Changing the masked result does not affect the original array.
This is different from slicing.

In [67]:
x = np.array([1.2, 4.1, 1.5, 4.5])
masked = x[x > 4]   # copy
masked[:] = 0

print("masked:", masked)
print("original x:", x)

masked: [0. 0.]
original x: [1.2 4.1 1.5 4.5]


## 10.6 Fancy indexing

Fancy indexing selects elements using index arrays (lists of indices).

This is useful to:
- pick specific points
- select a subset of rows/columns

Like masking, fancy indexing usually returns a **copy**.

### Select elements from a 1D array

In [68]:
x = np.array([7.0, 9.0, 6.0, 5.0])
print("x:", x)
print("x[[1, 3]]:", x[[1, 3]])

x: [7. 9. 6. 5.]
x[[1, 3]]: [9. 5.]


### Select rows from a 2D array

In [69]:
x = np.array([[0.0, 1.0, 2.0],
              [3.0, 4.0, 5.0],
              [6.0, 7.0, 8.0]])

print("x:\n", x)
print("\nx[[1, 2]] (rows 1 and 2):\n", x[[1, 2]])

x:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

x[[1, 2]] (rows 1 and 2):
 [[3. 4. 5.]
 [6. 7. 8.]]


### Select elements by coordinates

Use two index arrays: one for rows and one for columns.

This selects pairs:
- (row[0], col[0])
- (row[1], col[1])
- ...

In [70]:
x = np.array([[0.0, 1.0, 2.0],
              [3.0, 4.0, 5.0],
              [6.0, 7.0, 8.0]])

selected = x[[1, 2], [0, 2]]
print("selected:", selected)

selected: [3. 8.]


### Fancy indexing returns copies

Changing a selection does not change the original array.

In [71]:
x = np.array([1.2, 4.1, 1.5, 4.5])
sel = x[[1, 3]]
sel[:] = 0

print("sel:", sel)
print("original x:", x)

sel: [0. 0.]
original x: [1.2 4.1 1.5 4.5]


## 10.7 Combined indexing (basic idea)

You can mix slicing, masking, and fancy indexing.

Two practical rules:
1. Masking + slicing and fancy + slicing often keep the number of dimensions.
2. Simple indexing (taking a single element along an axis) usually removes that axis from the output.

Focus on the output `shape` to confirm what you got.

# 11. Working with arrays (reshape, concat)

These operations are used constantly when preparing numerical data:
- concatenating arrays
- reshaping between 1D and 2D
- adding new dimensions when needed

## 11.1 Concatenation

Concatenate arrays along an axis:
- `axis=0`: stack rows (increase number of rows)
- `axis=1`: stack columns (increase number of columns)

Arrays must match in shape on the non-concatenated axes.

In [74]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([[11, 12, 13],
              [14, 15, 16]])

print("concat axis=0:\n", np.concatenate((x, y), axis=0))
print("\nconcat axis=1:\n", np.concatenate((x, y), axis=1))

concat axis=0:
 [[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]

concat axis=1:
 [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


### hstack and vstack

- `np.hstack((x, y))` is like concatenating along columns for 2D arrays
- `np.vstack((x, y))` is like concatenating along rows

They are often more readable than `concatenate`.

In [75]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([[11, 12, 13],
              [14, 15, 16]])

h = np.hstack((x, y))
v = np.vstack((x, y))

print("hstack:\n", h)
print("\nvstack:\n", v)

hstack:
 [[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]

vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


### vstack with 1D vectors

`vstack` can create a new axis from 1D vectors (useful to build small matrices).

In [76]:
x = np.array([1, 2, 3])
y = np.array([11, 12, 13])

v = np.vstack((x, y))
print(v)
print("shape:", v.shape)

[[ 1  2  3]
 [11 12 13]]
shape: (2, 3)


## 11.2 Reshaping arrays

`reshape` changes how the same data is interpreted across dimensions.

Example: turn a vector of length 6 into a 2x3 matrix.

Important:
- total number of elements must stay the same

In [81]:
x = np.arange(6)
y = x.reshape((2, 3))

print("x:", x)
print("y:\n", y)
print("x.size:", x.size, "y.size:", y.size)

x: [0 1 2 3 4 5]
y:
 [[0 1 2]
 [3 4 5]]
x.size: 6 y.size: 6


### Using -1 in reshape

You can let NumPy infer one dimension by using `-1`.

Typical use:
- convert a 1D vector into a column vector (`(n, 1)`)
- or into a row vector (`(1, n)`)

In [83]:
x = np.array([1, 2, 3])
col = x.reshape(-1, 1)
row = x.reshape(1, -1)

print("x shape:", x.shape)
print("col shape:", col.shape)
print("row shape:", row.shape)
print("\ncol:\n", col)
print("\nrow:\n", row)

x shape: (3,)
col shape: (3, 1)
row shape: (1, 3)

col:
 [[1]
 [2]
 [3]]

row:
 [[1 2 3]]


## 11.4 Adding new dimensions (np.newaxis)

`np.newaxis` inserts a new dimension of size 1.

This is useful when you want shapes to match for broadcasting or dot products.

Example: convert a 2D array with shape `(2, 3)` into `(1, 2, 3)`.

In [84]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

res = arr[np.newaxis, :, :]
print("arr shape:", arr.shape)
print("res shape:", res.shape)
print(res)

arr shape: (2, 3)
res shape: (1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


### Application: 1D vector to column vector

This is an alternative to `reshape(-1, 1)`.

In [85]:
arr = np.array([1, 2, 3])
col = arr[:, np.newaxis]

print("arr shape:", arr.shape)
print("col shape:", col.shape)
print(col)

arr shape: (3,)
col shape: (3, 1)
[[1]
 [2]
 [3]]
